// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvP04eGtKNKw6h8oOi4nnDY3oPNQhLT4',
    appId: '1:132904533499:web:b184c5182384be316a9f5e',
    messagingSenderId: '132904533499',
    projectId: 'joulslabs',
    authDomain: 'joulslabs.firebaseapp.com',
    storageBucket: 'joulslabs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvqqrpG5nqSgKrNgBIK-KCP6vjk4TSdqk',
    appId: '1:132904533499:android:ecb7e2d2216539ae6a9f5e',
    messagingSenderId: '132904533499',
    projectId: 'joulslabs',
    storageBucket: 'joulslabs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2V6Pau_6Of267w4_Ro51P0eoRf_YslJE',
    appId: '1:132904533499:ios:f71e2c4e1ffa40ba6a9f5e',
    messagingSenderId: '132904533499',
    projectId: 'joulslabs',
    storageBucket: 'joulslabs.appspot.com',
    iosClientId: '132904533499-pl96u47bbejl7jfq6bgn8c4rgn35o4re.apps.googleusercontent.com',
    iosBundleId: 'com.example.joulsLabsDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2V6Pau_6Of267w4_Ro51P0eoRf_YslJE',
    appId: '1:132904533499:ios:f5afd4487017c5916a9f5e',
    messagingSenderId: '132904533499',
    projectId: 'joulslabs',
    storageBucket: 'joulslabs.appspot.com',
    iosClientId: '132904533499-dmpm93okm1g55cbkrmp5tptntvpm7ctk.apps.googleusercontent.com',
    iosBundleId: 'com.example.joulsLabsDemoApp.RunnerTests',
  );
}
